// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAobEWXLWkZ6qZpdBxNpQw9mVbUd_v0Fq4',
    appId: '1:863987146184:web:25895ffc95d312236874fd',
    messagingSenderId: '863987146184',
    projectId: 'stylehub-31943',
    authDomain: 'stylehub-31943.firebaseapp.com',
    storageBucket: 'stylehub-31943.firebasestorage.app',
    measurementId: 'G-PH5TYRL7BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXf2booQn8YwzVHGjrF-U30sqvzjYhVsA',
    appId: '1:863987146184:android:bc4fde34f5a324a76874fd',
    messagingSenderId: '863987146184',
    projectId: 'stylehub-31943',
    storageBucket: 'stylehub-31943.firebasestorage.app',
  );
}
